In [1]:
import pandas as pd

In [3]:
df1 = pd.read_csv("/Users/kruthikhulisandra/Desktop/SpotifyProject/Datasets/merged_songs.csv")
df2 = pd.read_csv("/Users/kruthikhulisandra/Desktop/SpotifyProject/Datasets/dfSCleaned.csv")

In [5]:
df = pd.merge(df1, df2, left_on='Track ID', right_on='spotifyID', how='inner')

In [7]:
df

,Track ID,Track Name,Album Name,Artist Name(s),Release Date,Duration (ms),Popularity,Added By,Added At,Genres,...,artist_name,album_name,ms_played,spotifyID,reason_start,reason_end,shuffle,skipped,offline,incognito_mode
0,4bw3ZyWA1ui0Adu285NWDl,Without Me - ILLENIUM Remix,Without Me (ILLENIUM Remix),"Halsey,ILLENIUM",2018-11-30,248906.0,49.0,NaN,2025-01-31T05:00:28Z,"melodic bass,future bass,edm",...,Halsey,Without Me,0,4bw3ZyWA1ui0Adu285NWDl,fwdbtn,fwdbtn,False,False,False,False
1,4bw3ZyWA1ui0Adu285NWDl,Without Me - ILLENIUM Remix,Without Me (ILLENIUM Remix),"Halsey,ILLENIUM",2018-11-30,248906.0,49.0,NaN,2025-01-31T05:00:28Z,"melodic bass,future bass,edm",...,Halsey,Without Me,2730,4bw3ZyWA1ui0Adu285NWDl,fwdbtn,fwdbtn,True,False,False,False
2,4bw3ZyWA1ui0Adu285NWDl,Without Me - ILLENIUM Remix,Without Me (ILLENIUM Remix),"Halsey,ILLENIUM",2018-11-30,248906.0,49.0,NaN,2025-01-31T05:00:28Z,"melodic bass,future bass,edm",...,Halsey,Without Me,85564,4bw3ZyWA1ui0Adu285NWDl,trackdone,fwdbtn,True,False,False,False
3,4bw3ZyWA1ui0Adu285NWDl,Without Me - ILLENIUM Remix,Without Me (ILLENIUM Remix),"Halsey,ILLENIUM",2018-11-30,248906.0,49.0,NaN,2025-01-31T05:00:28Z,"melodic bass,future bass,edm",...,Halsey,Without Me,1414,4bw3ZyWA1ui0Adu285NWDl,fwdbtn,fwdbtn,False,True,False,False
4,4bw3ZyWA1ui0Adu285NWDl,Without Me - ILLENIUM Remix,Without Me (ILLENIUM Remix),"Halsey,ILLENIUM",2018-11-30,248906.0,49.0,NaN,2025-01-31T05:00:28Z,"melodic bass,future bass,edm",...,Halsey,Without Me,248906,4bw3ZyWA1ui0Adu285NWDl,clickrow,endplay,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31923,1Y7UkYVReK4z5hgm0121SS,Sink Your Teeth In,.wav,"Flux Pavilion,Drowsy",2021-01-21,203579.0,0.0,NaN,2021-11-01T15:42:45Z,"dubstep,edm,dub,melodic bass,future bass",...,Flux Pavilion,.wav,173330,1Y7UkYVReK4z5hgm0121SS,trackdone,trackdone,False,False,False,False
31924,1Y7UkYVReK4z5hgm0121SS,Sink Your Teeth In,.wav,"Flux Pavilion,Drowsy",2021-01-21,203579.0,0.0,NaN,2021-11-01T15:42:45Z,"dubstep,edm,dub,melodic bass,future bass",...,Flux Pavilion,.wav,3134,1Y7UkYVReK4z5hgm0121SS,playbtn,fwdbtn,True,True,False,False
31925,1Y7UkYVReK4z5hgm0121SS,Sink Your Teeth In,.wav,"Flux Pavilion,Drowsy",2021-01-21,203579.0,0.0,NaN,2021-11-01T15:42:45Z,"dubstep,edm,dub,melodic bass,future bass",...,Flux Pavilion,.wav,203579,1Y7UkYVReK4z5hgm0121SS,trackdone,trackdone,True,False,False,False
31926,1Y7UkYVReK4z5hgm0121SS,Sink Your Teeth In,.wav,"Flux Pavilion,Drowsy",2021-01-21,203579.0,0.0,NaN,2021-11-01T15:42:45Z,"dubstep,edm,dub,melodic bass,future bass",...,Flux Pavilion,.wav,203579,1Y7UkYVReK4z5hgm0121SS,trackdone,trackdone,True,False,False,False
31927,1Y7UkYVReK4z5hgm0121SS,Sink Your Teeth In,.wav,"Flux Pavilion,Drowsy",2021-01-21,203579.0,0.0,NaN,2021-11-01T15:42:45Z,"dubstep,edm,dub,melodic bass,future bass",...,Flux Pavilion,.wav,1053,1Y7UkYVReK4z5hgm0121SS,trackdone,fwdbtn,True,True,False,False

In [9]:
df = df.drop(columns=['spotifyID'])

In [11]:
df.columns

Index(['Track ID', 'Track Name', 'Album Name', 'Artist Name(s)',
       'Release Date', 'Duration (ms)', 'Popularity', 'Added By', 'Added At',
       'Genres', 'Record Label', 'Danceability', 'Energy', 'Key', 'Loudness',
       'Mode', 'Speechiness', 'Acousticness', 'Instrumentalness', 'Liveness',
       'Valence', 'Tempo', 'Time Signature', 'date', 'time', 'conn_country',
       'platform', 'track_name', 'artist_name', 'album_name', 'ms_played',
       'reason_start', 'reason_end', 'shuffle', 'skipped', 'offline',
       'incognito_mode'],
      dtype='object')

In [19]:

# 1️⃣ Normalize column names
df.columns = (
    df.columns
      .str.strip()                 # remove leading/trailing spaces
      .str.lower()                 # make lowercase
      .str.replace(r'\s+', '_', regex=True)  # replace spaces with underscores
      .str.replace(r'_x$|_y$', '', regex=True)  # remove merge suffixes
)

# 2️⃣ Drop duplicate column names (now case-insensitive)
df = df.loc[:, ~df.columns.duplicated()]

# 3️⃣ Move 'date' and 'time' to positions 2 and 3
cols = df.columns.tolist()
cols.insert(1, cols.pop(cols.index('date')))
cols.insert(2, cols.pop(cols.index('time')))
df = df[cols]

In [21]:
df

,track_id,date,time,track_name,album_name,artist_name(s),release_date,duration_(ms),popularity,added_by,...,conn_country,platform,artist_name,ms_played,reason_start,reason_end,shuffle,skipped,offline,incognito_mode
0,4bw3ZyWA1ui0Adu285NWDl,2022-02-10,01:36:21,Without Me - ILLENIUM Remix,Without Me (ILLENIUM Remix),"Halsey,ILLENIUM",2018-11-30,248906.0,49.0,NaN,...,US,ios,Halsey,0,fwdbtn,fwdbtn,False,False,False,False
1,4bw3ZyWA1ui0Adu285NWDl,2022-03-30,19:04:41,Without Me - ILLENIUM Remix,Without Me (ILLENIUM Remix),"Halsey,ILLENIUM",2018-11-30,248906.0,49.0,NaN,...,US,ios,Halsey,2730,fwdbtn,fwdbtn,True,False,False,False
2,4bw3ZyWA1ui0Adu285NWDl,2022-04-17,19:50:25,Without Me - ILLENIUM Remix,Without Me (ILLENIUM Remix),"Halsey,ILLENIUM",2018-11-30,248906.0,49.0,NaN,...,US,ios,Halsey,85564,trackdone,fwdbtn,True,False,False,False
3,4bw3ZyWA1ui0Adu285NWDl,2023-07-07,19:07:16,Without Me - ILLENIUM Remix,Without Me (ILLENIUM Remix),"Halsey,ILLENIUM",2018-11-30,248906.0,49.0,NaN,...,US,not_applicable,Halsey,1414,fwdbtn,fwdbtn,False,True,False,False
4,4bw3ZyWA1ui0Adu285NWDl,2023-12-01,07:56:24,Without Me - ILLENIUM Remix,Without Me (ILLENIUM Remix),"Halsey,ILLENIUM",2018-11-30,248906.0,49.0,NaN,...,US,ios,Halsey,248906,clickrow,endplay,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31923,1Y7UkYVReK4z5hgm0121SS,2023-11-30,03:51:01,Sink Your Teeth In,.wav,"Flux Pavilion,Drowsy",2021-01-21,203579.0,0.0,NaN,...,US,ios,Flux Pavilion,173330,trackdone,trackdone,False,False,False,False
31924,1Y7UkYVReK4z5hgm0121SS,2024-01-01,18:55:00,Sink Your Teeth In,.wav,"Flux Pavilion,Drowsy",2021-01-21,203579.0,0.0,NaN,...,US,ios,Flux Pavilion,3134,playbtn,fwdbtn,True,True,False,False
31925,1Y7UkYVReK4z5hgm0121SS,2024-01-24,04:14:27,Sink Your Teeth In,.wav,"Flux Pavilion,Drowsy",2021-01-21,203579.0,0.0,NaN,...,US,ios,Flux Pavilion,203579,trackdone,trackdone,True,False,False,False
31926,1Y7UkYVReK4z5hgm0121SS,2024-02-25,07:14:39,Sink Your Teeth In,.wav,"Flux Pavilion,Drowsy",2021-01-21,203579.0,0.0,NaN,...,US,osx,Flux Pavilion,203579,trackdone,trackdone,True,False,False,False
31927,1Y7UkYVReK4z5hgm0121SS,2024-05-05,15:10:05,Sink Your Teeth In,.wav,"Flux Pavilion,Drowsy",2021-01-21,203579.0,0.0,NaN,...,US,osx,Flux Pavilion,1053,trackdone,fwdbtn,True,True,False,False

In [23]:
df.shape

(31928, 35)

In [25]:
keep_cols = [
    # Identification & Time
    'track_id', 'date', 'time',
    
    # Playback Session Details
    'conn_country', 'platform', 'ms_played', 'skipped',
    'reason_start', 'reason_end', 'shuffle', 'offline', 'incognito_mode',
    
    # Song Metadata
    'track_name', 'artist_name', 'album_name', 'genres', 'release_date',
    'record_label', 'added_by', 'added_at',
    
    # Audio Features
    'duration_(ms)', 'popularity',
    'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness',
    'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo',
    'time_signature'
]

In [27]:
df = df[keep_cols]

In [31]:
df.shape

(31928, 34)

In [33]:
df

,track_id,date,time,conn_country,platform,ms_played,skipped,reason_start,reason_end,shuffle,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,4bw3ZyWA1ui0Adu285NWDl,2022-02-10,01:36:21,US,ios,0,False,fwdbtn,fwdbtn,False,...,6.0,-3.358,1.0,0.0479,0.48300,0.000002,0.219,0.373,136.004,4.0
1,4bw3ZyWA1ui0Adu285NWDl,2022-03-30,19:04:41,US,ios,2730,False,fwdbtn,fwdbtn,True,...,6.0,-3.358,1.0,0.0479,0.48300,0.000002,0.219,0.373,136.004,4.0
2,4bw3ZyWA1ui0Adu285NWDl,2022-04-17,19:50:25,US,ios,85564,False,trackdone,fwdbtn,True,...,6.0,-3.358,1.0,0.0479,0.48300,0.000002,0.219,0.373,136.004,4.0
3,4bw3ZyWA1ui0Adu285NWDl,2023-07-07,19:07:16,US,not_applicable,1414,True,fwdbtn,fwdbtn,False,...,6.0,-3.358,1.0,0.0479,0.48300,0.000002,0.219,0.373,136.004,4.0
4,4bw3ZyWA1ui0Adu285NWDl,2023-12-01,07:56:24,US,ios,248906,True,clickrow,endplay,False,...,6.0,-3.358,1.0,0.0479,0.48300,0.000002,0.219,0.373,136.004,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31923,1Y7UkYVReK4z5hgm0121SS,2023-11-30,03:51:01,US,ios,173330,False,trackdone,trackdone,False,...,3.0,-7.351,1.0,0.0844,0.00548,0.382000,0.186,0.266,150.069,4.0
31924,1Y7UkYVReK4z5hgm0121SS,2024-01-01,18:55:00,US,ios,3134,True,playbtn,fwdbtn,True,...,3.0,-7.351,1.0,0.0844,0.00548,0.382000,0.186,0.266,150.069,4.0
31925,1Y7UkYVReK4z5hgm0121SS,2024-01-24,04:14:27,US,ios,203579,False,trackdone,trackdone,True,...,3.0,-7.351,1.0,0.0844,0.00548,0.382000,0.186,0.266,150.069,4.0
31926,1Y7UkYVReK4z5hgm0121SS,2024-02-25,07:14:39,US,osx,203579,False,trackdone,trackdone,True,...,3.0,-7.351,1.0,0.0844,0.00548,0.382000,0.186,0.266,150.069,4.0
31927,1Y7UkYVReK4z5hgm0121SS,2024-05-05,15:10:05,US,osx,1053,True,trackdone,fwdbtn,True,...,3.0,-7.351,1.0,0.0844,0.00548,0.382000,0.186,0.266,150.069,4.0

In [39]:
print(df.head(5))

                 track_id        date      time conn_country        platform  \
0  4bw3ZyWA1ui0Adu285NWDl  2022-02-10  01:36:21           US             ios
1  4bw3ZyWA1ui0Adu285NWDl  2022-03-30  19:04:41           US             ios
2  4bw3ZyWA1ui0Adu285NWDl  2022-04-17  19:50:25           US             ios
3  4bw3ZyWA1ui0Adu285NWDl  2023-07-07  19:07:16           US  not_applicable
4  4bw3ZyWA1ui0Adu285NWDl  2023-12-01  07:56:24           US             ios

   ms_played  skipped reason_start reason_end  shuffle  offline  \
0          0    False       fwdbtn     fwdbtn    False    False
1       2730    False       fwdbtn     fwdbtn     True    False
2      85564    False    trackdone     fwdbtn     True    False
3       1414     True       fwdbtn     fwdbtn    False    False
4     248906     True     clickrow    endplay    False    False

   incognito_mode                   track_name artist_name  \
0           False  Without Me - ILLENIUM Remix      Halsey
1           False  Without Me - ILLENIUM Remix      Halsey
2           False  Without Me - ILLENIUM Remix      Halsey
3           False  Without Me - ILLENIUM Remix      Halsey
4           False  Without Me - ILLENIUM Remix      Halsey

                    album_name                        genres release_date  \
0  Without Me (ILLENIUM Remix)  melodic bass,future bass,edm   2018-11-30
1  Without Me (ILLENIUM Remix)  melodic bass,future bass,edm   2018-11-30
2  Without Me (ILLENIUM Remix)  melodic bass,future bass,edm   2018-11-30
3  Without Me (ILLENIUM Remix)  melodic bass,future bass,edm   2018-11-30
4  Without Me (ILLENIUM Remix)  melodic bass,future bass,edm   2018-11-30

      record_label added_by              added_at  duration_(ms)  popularity  \
0  Capitol Records      NaN  2025-01-31T05:00:28Z       248906.0        49.0
1  Capitol Records      NaN  2025-01-31T05:00:28Z       248906.0        49.0
2  Capitol Records      NaN  2025-01-31T05:00:28Z       248906.0        49.0
3  Capitol Records      NaN  2025-01-31T05:00:28Z       248906.0        49.0
4  Capitol Records      NaN  2025-01-31T05:00:28Z       248906.0        49.0

   danceability  energy  key  loudness  mode  speechiness  acousticness  \
0         0.639    0.71  6.0    -3.358   1.0       0.0479         0.483
1         0.639    0.71  6.0    -3.358   1.0       0.0479         0.483
2         0.639    0.71  6.0    -3.358   1.0       0.0479         0.483
3         0.639    0.71  6.0    -3.358   1.0       0.0479         0.483
4         0.639    0.71  6.0    -3.358   1.0       0.0479         0.483

   instrumentalness  liveness  valence    tempo  time_signature
0          0.000002     0.219    0.373  136.004             4.0
1          0.000002     0.219    0.373  136.004             4.0
2          0.000002     0.219    0.373  136.004             4.0
3          0.000002     0.219    0.373  136.004             4.0
4          0.000002     0.219    0.373  136.004             4.0

In [37]:
pd.set_option('display.max_columns', None)